"""create full schema

Revision ID: 68a5fc9fc7d4
Revises:
Create Date: 2026-09-05 20:27:53.078440

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # los tipos AutoString de SQLModel salen aqui

from alembic import op

revision: str = "68a5fc9fc7d4"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("adapter_type", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("ble_name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
        sa.Column("ble_address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("auto_connect", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_devices_adapter_type"), ["adapter_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_devices_ble_address"), ["ble_address"], unique=False)
        batch_op.create_index(batch_op.f("ix_devices_ble_name"), ["ble_name"], unique=False)
        batch_op.create_index(batch_op.f("ix_devices_name"), ["name"], unique=False)

    op.create_table(
        "effects",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(length=40), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("loop", sa.Boolean(), nullable=False),
        sa.Column("speed", sa.Integer(), nullable=False),
        sa.Column("fps", sa.Integer(), nullable=False),
        sa.Column("transition_ms", sa.Integer(), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("fps >= 1 AND fps <= 60", name="ck_effects_fps"),
        sa.CheckConstraint("speed >= 0 AND speed <= 100", name="ck_effects_speed"),
        sa.CheckConstraint("transition_ms >= 0", name="ck_effects_transition_ms"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("effects", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_effects_name"), ["name"], unique=False)
        batch_op.create_index(batch_op.f("ix_effects_type"), ["type"], unique=False)

    op.create_table(
        "profiles",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_profiles_name"), ["name"], unique=False)

    op.create_table(
        "scenes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(length=80), nullable=True),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scenes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scenes_name"), ["name"], unique=False)

    op.create_table(
        "device_capabilities",
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("supports_rgb", sa.Boolean(), nullable=False),
        sa.Column("supports_brightness", sa.Boolean(), nullable=False),
        sa.Column("supports_effects", sa.Boolean(), nullable=False),
        sa.Column("addressable", sa.Boolean(), nullable=False),
        sa.Column("supports_segments", sa.Boolean(), nullable=False),
        sa.Column("white_channel", sa.Boolean(), nullable=False),
        sa.Column("music_mode", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("device_id"),
    )
    op.create_table(
        "device_state",
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("power", sa.Boolean(), nullable=False),
        sa.Column("color_hex", sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
        sa.Column("brightness", sa.Integer(), nullable=False),
        sa.Column("active_scene_id", sa.Uuid(), nullable=True),
        sa.Column("active_effect_id", sa.Uuid(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "color_hex GLOB '#[0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F][0-9A-F]'",
            name="ck_device_state_color_hex",
        ),
        sa.CheckConstraint(
            "brightness >= 0 AND brightness <= 100", name="ck_device_state_brightness"
        ),
        sa.ForeignKeyConstraint(["active_effect_id"], ["effects.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["active_scene_id"], ["scenes.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("device_id"),
    )
    op.create_table(
        "effect_steps",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("effect_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("color_hex", sqlmodel.sql.sqltypes.AutoString(length=7), nullable=False),
        sa.Column("brightness", sa.Integer(), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("easing", sqlmodel.sql.sqltypes.AutoString(length=30), nullable=True),
        sa.CheckConstraint(
            "brightness IS NULL OR (brightness >= 0 AND brightness <= 100)",
            name="ck_effect_steps_brightness",
        ),
        sa.CheckConstraint(
            "duration_ms IS NULL OR duration_ms >= 0", name="ck_effect_steps_duration_ms"
        ),
        sa.CheckConstraint("position >= 0", name="ck_effect_steps_position"),
        sa.ForeignKeyConstraint(["effect_id"], ["effects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("effect_id", "position", name="uq_effect_steps_effect_position"),
    )
    with op.batch_alter_table("effect_steps", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_effect_steps_effect_id"), ["effect_id"], unique=False)

    op.create_table(
        "profile_scenes",
        sa.Column("profile_id", sa.Uuid(), nullable=False),
        sa.Column("scene_id", sa.Uuid(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.CheckConstraint("position >= 0", name="ck_profile_scenes_position"),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("profile_id", "scene_id"),
    )
    with op.batch_alter_table("profile_scenes", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_profile_scenes_scene_id"), ["scene_id"], unique=False)

    op.create_table(
        "scene_targets",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("scene_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.Uuid(), nullable=False),
        sa.Column("effect_id", sa.Uuid(), nullable=False),
        sa.Column("brightness", sa.Integer(), nullable=True),
        sa.Column("speed", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "brightness IS NULL OR (brightness >= 0 AND brightness <= 100)",
            name="ck_scene_targets_brightness",
        ),
        sa.CheckConstraint(
            "speed IS NULL OR (speed >= 0 AND speed <= 100)", name="ck_scene_targets_speed"
        ),
        sa.ForeignKeyConstraint(["device_id"], ["devices.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["effect_id"], ["effects.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("scene_id", "device_id", name="uq_scene_targets_scene_device"),
    )
    with op.batch_alter_table("scene_targets", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scene_targets_device_id"), ["device_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scene_targets_effect_id"), ["effect_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_scene_targets_scene_id"), ["scene_id"], unique=False)

    op.create_table(
        "schedules",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=120), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("at_time", sa.Time(), nullable=False),
        sa.Column("days_of_week", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("scene_id", sa.Uuid(), nullable=True),
        sa.Column("profile_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint(
            "(scene_id IS NOT NULL AND profile_id IS NULL) OR (scene_id IS NULL AND profile_id IS NOT NULL)",
            name="ck_schedules_single_target",
        ),
        sa.ForeignKeyConstraint(["profile_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["scene_id"], ["scenes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_schedules_at_time"), ["at_time"], unique=False)
        batch_op.create_index(batch_op.f("ix_schedules_enabled"), ["enabled"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedules", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_schedules_enabled"))
        batch_op.drop_index(batch_op.f("ix_schedules_at_time"))

    op.drop_table("schedules")
    with op.batch_alter_table("scene_targets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scene_targets_scene_id"))
        batch_op.drop_index(batch_op.f("ix_scene_targets_effect_id"))
        batch_op.drop_index(batch_op.f("ix_scene_targets_device_id"))

    op.drop_table("scene_targets")
    with op.batch_alter_table("profile_scenes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_profile_scenes_scene_id"))

    op.drop_table("profile_scenes")
    with op.batch_alter_table("effect_steps", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_effect_steps_effect_id"))

    op.drop_table("effect_steps")
    op.drop_table("device_state")
    op.drop_table("device_capabilities")
    with op.batch_alter_table("scenes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scenes_name"))

    op.drop_table("scenes")
    with op.batch_alter_table("profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_profiles_name"))

    op.drop_table("profiles")
    with op.batch_alter_table("effects", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_effects_type"))
        batch_op.drop_index(batch_op.f("ix_effects_name"))

    op.drop_table("effects")
    with op.batch_alter_table("devices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_devices_name"))
        batch_op.drop_index(batch_op.f("ix_devices_ble_name"))
        batch_op.drop_index(batch_op.f("ix_devices_ble_address"))
        batch_op.drop_index(batch_op.f("ix_devices_adapter_type"))

    op.drop_table("devices")
    # ### end Alembic commands ###
